### ISSUE TITLE
issue not checking out

### ISSUE THREAD

**Issue by themuffinman26** [kareemelgendy/RestockBot#3]
smokeandmirrorshobby.com
product adds to cart (just using yugioh blazing vortex booster box to test as its in stock.
already logged in
gets to end but doesn't hit the button pay now.
any thoughts?

just some inspection
/button class=c0fok_32pNS" aria-busy
html body div#app.FullHeightApp section._1CoOG div._3d-Au div._3N6iG div._39SW-._2dQzu._160BV.ioQcb div._39SW-._3IT_5 button.cOfoK._32pNS
.cOfoK
/html/body/div/section/div[1]/div[2]/div[3]/div[2]/button
/html/body/div/section/div[1]/div[2]/div[3]/div[2]/button

**Comment by kareemelgendy** [comment]
Auto checkout is not implemented yet, should be working in the next update.

**Comment by themuffinman26** [comment]
Ahh I see. Great job otherwise. Can't wait for update! I have some other scripts that I'll see if I can get checkout to work on with your code.
