### ISSUE TITLE
How do I change the quantity to purchase?

### ISSUE THREAD

**Issue by themuffinman26** [kareemelgendy/RestockBot#4]
Great code. Had a quick question. Is there a way to purchase more than one of an item? Like add two or three to cart then check out?

**Comment by kareemelgendy** [comment]
The product is saved in the dictionary with the name as the key. So, adding the same item in two different variants is not possible yet, but you can modify the number of items you want to cart by changing the '1' on line 197 of the utilities.py file (cart_url) to your desired amount.
